gitRepoUrl = "https://github.com/ColRealPro/SimplyReplicate"
gitSourceBranch = "main"

title = "SimplyReplicate"
classOrder = [
	"Replicator",
	"Signal"
]

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "A simple easy to use replication system for Roblox"